### ISSUE TITLE
Missing description under title

### ISSUE THREAD

**Issue by lfarah** [jackyzh/awesome-ios-animation#2]
<img width="424" alt="screen shot 2016-07-16 at 11 55 03 pm" src="https://cloud.githubusercontent.com/assets/6511079/16898429/bb3df97e-4bb0-11e6-8e2d-b3ee121002ef.png">

**Comment by jzau** [comment]
I added awesome iOS animation at this time, feel free to contact me if you have a better idea. cheers!

**Comment by lfarah** [comment]
I think that it could be more descriptive. Something like:

> Curated list of iOS Animation libraries

**Comment by jzau** [comment]
Thanks for that, I've updated it.
